#----------------------------------------------------------------
# Generated CMake target import file for configuration "Debug".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKXSBase" for configuration "Debug"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKXSBase.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKXSBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSBase "${_IMPORT_PREFIX}/libd/TKXSBase.lib" "${_IMPORT_PREFIX}/bind/TKXSBase.dll" )

# Import target "TKSTEPBase" for configuration "Debug"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKSTEPBase.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKSTEPBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPBase "${_IMPORT_PREFIX}/libd/TKSTEPBase.lib" "${_IMPORT_PREFIX}/bind/TKSTEPBase.dll" )

# Import target "TKSTEPAttr" for configuration "Debug"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKSTEPAttr.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKSTEPAttr.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPAttr )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPAttr "${_IMPORT_PREFIX}/libd/TKSTEPAttr.lib" "${_IMPORT_PREFIX}/bind/TKSTEPAttr.dll" )

# Import target "TKSTEP209" for configuration "Debug"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKSTEP209.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKSTEP209.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP209 )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP209 "${_IMPORT_PREFIX}/libd/TKSTEP209.lib" "${_IMPORT_PREFIX}/bind/TKSTEP209.dll" )

# Import target "TKSTEP" for configuration "Debug"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKSTEP.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKSTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP "${_IMPORT_PREFIX}/libd/TKSTEP.lib" "${_IMPORT_PREFIX}/bind/TKSTEP.dll" )

# Import target "TKIGES" for configuration "Debug"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKIGES.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKIGES "${_IMPORT_PREFIX}/libd/TKIGES.lib" "${_IMPORT_PREFIX}/bind/TKIGES.dll" )

# Import target "TKXCAF" for configuration "Debug"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKXCAF.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXCAF "${_IMPORT_PREFIX}/libd/TKXCAF.lib" "${_IMPORT_PREFIX}/bind/TKXCAF.dll" )

# Import target "TKXDEIGES" for configuration "Debug"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKXDEIGES.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKXDEIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXDEIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXDEIGES "${_IMPORT_PREFIX}/libd/TKXDEIGES.lib" "${_IMPORT_PREFIX}/bind/TKXDEIGES.dll" )

# Import target "TKXDESTEP" for configuration "Debug"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKXDESTEP.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKXDESTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXDESTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXDESTEP "${_IMPORT_PREFIX}/libd/TKXDESTEP.lib" "${_IMPORT_PREFIX}/bind/TKXDESTEP.dll" )

# Import target "TKSTL" for configuration "Debug"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKSTL.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKSTL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTL "${_IMPORT_PREFIX}/libd/TKSTL.lib" "${_IMPORT_PREFIX}/bind/TKSTL.dll" )

# Import target "TKVRML" for configuration "Debug"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKVRML.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKVRML.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKVRML )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKVRML "${_IMPORT_PREFIX}/libd/TKVRML.lib" "${_IMPORT_PREFIX}/bind/TKVRML.dll" )

# Import target "TKXmlXCAF" for configuration "Debug"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKXmlXCAF.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKXmlXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlXCAF "${_IMPORT_PREFIX}/libd/TKXmlXCAF.lib" "${_IMPORT_PREFIX}/bind/TKXmlXCAF.dll" )

# Import target "TKBinXCAF" for configuration "Debug"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKBinXCAF.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKBinXCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinXCAF "${_IMPORT_PREFIX}/libd/TKBinXCAF.lib" "${_IMPORT_PREFIX}/bind/TKBinXCAF.dll" )

# Import target "TKRWMesh" for configuration "Debug"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/libd/TKRWMesh.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bind/TKRWMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKRWMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKRWMesh "${_IMPORT_PREFIX}/libd/TKRWMesh.lib" "${_IMPORT_PREFIX}/bind/TKRWMesh.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
